### PR TITLE
fix TransformerQA predictor test

### PR DESCRIPTION
**Pull request by epwalsh**
Quick fix to an oversight I missed in the SQuAD updates. This test randomly fails sometimes. This fixes that.

### CODE REVIEW

**Review by dirkgr — COMMENTED** [review]
Can we just replace the example with something that shouldn't fail?

**Comment by dirkgr** [comment]
Oh, it's running an untrained model. So no amount of sense in the example will make this behave properly.

**Comment by epwalsh** [comment]
Right

**Review by dirkgr — APPROVED** [review]
This is kind of a screwy test now, but Akshita is depending on this being merged right now, so let's merge it and fix it if it becomes a problem later.

**Pull request merged**
