### PR TITLE
Missing perl error message

### PR DESCRIPTION
**Pull request by dirkgr**
Fixes https://github.com/allenai/allennlp/issues/5573.

### CODE REVIEW

**Comment by dirkgr** [comment]
There is now nothing left of this PR, but thanks to squash merging, GitHub can't figure this out automatically.

**Comment by Denbergvanthijs** [comment]
Thank you very much! Just a quick suggestion: wouldn't `from shutil import which` be a cleaner option instead of a try-except? [It looks to be multiplatform ](https://docs.python.org/3/library/shutil.html) and available since Python 3.3. When the executable is not found, it returns None.

**Comment by dirkgr** [comment]
While unlikely, that introduces a race condition. What if someone moves the perl executable after your call to `which` and before the call to `subprocess.run`?

**Comment by Denbergvanthijs** [comment]
That would indeed be a possibility, thank you for your answer!

**Pull request closed without merging**
