### PR TITLE
MST decoding

### PR DESCRIPTION
**Pull request by dirkgr**
Having MST decoding off breaks when it runs as a predictor, in the demo. It would be easiest if we could just train with it on. I'm trying that now and comparing the scores.

### CODE REVIEW

**Comment by dirkgr** [comment]
Scores are virtually identical. Before:
```
  "best_validation_UAS": 0.9500837988826816,
  "best_validation_LAS": 0.9381284916201117,
  "best_validation_UEM": 0.55,
  "best_validation_LEM": 0.48705882352941177,
  "best_validation_loss": 0.464306292789323
```
After:
```
  "best_validation_UAS": 0.9500558659217877,
  "best_validation_LAS": 0.9381284916201117,
  "best_validation_UEM": 0.5547058823529412,
  "best_validation_LEM": 0.49117647058823527,
  "best_validation_loss": 0.464306292789323
```

**Comment by matt-gardner** [comment]
Why does it break when running in the demo?  And does this affect running times?

**Comment by dirkgr** [comment]
It breaks in the demo because only with MST are we guaranteed a well-formed tree.

**Comment by dirkgr** [comment]
There is no practical difference in training times. I'm not sure that algorithm is slow anyways, because the sentences are pretty short. Also, the change only applies to validation, and the validation set is not that big.

**Pull request merged**
