### PR TITLE
Demo Sweep 2

### PR DESCRIPTION
**Pull request by dirkgr**

### CODE REVIEW

**Review by epwalsh — APPROVED** [review]
LGTM other than the failing test for pretrained ViLBERT

**Comment by dirkgr** [comment]
@AkshitaB, should I wait until your VQA fix is merged?

**Comment by jonborchardt** [comment]
looks good

**Comment by dirkgr** [comment]
Wrong PR? Did you mean to look at https://github.com/allenai/allennlp-demo/pull/888? This one is already merged.

**Pull request merged**
