### PR TITLE
Fix capitalization typo in SNLI RoBERTa config

### PR DESCRIPTION
**Pull request by matt-gardner**
We aren't testing these at all, are we?  Is there a relatively easy way to make sure we're doing some minimal tests for these?

### CODE REVIEW

**Comment by epwalsh** [comment]
> We aren't testing these at all, are we? Is there a relatively easy way to make sure we're doing some minimal tests for these?

I've thought about this a little. It would be really great if we had a quick, general way to validate configuration files.

**Comment by matt-gardner** [comment]
> I've thought about this a little. It would be really great if we had a quick, general way to validate configuration files.

I had a simple suggestion here: https://github.com/allenai/allennlp/issues/3649#issuecomment-575926448.

**Comment by epwalsh** [comment]
@matt-gardner should we make this a Milestone 1.1 priority?

**Comment by matt-gardner** [comment]
I'll add that issue to the milestone, so we at least consider it.  Easy to move it out if we decide not to do it.

**Pull request merged**
