### PR TITLE
Fix small bugs in RC model

### PR DESCRIPTION
**Pull request by gladuo**

### CODE REVIEW

**Review by epwalsh — APPROVED** [review]
These changes LGTM, but how did the fix the dead lock? Or what was the reason for the dead lock in the first place?

**Comment by epwalsh** [comment]
Also please run `black .` to fix the formatting issues when you get a chance

**Comment by gladuo** [comment]
> These changes LGTM, but how did this fix the dead lock? Or what was the reason for the dead lock in the first place?
@epwalsh 
emmm... I might confuse you, but those changes above did NOT fix the dead lock, and they only fixed some other critical bugs in rc models.
I have not figured out what on earth made the dead lock, and I just bypassed it using drop_last by now.

**Comment by epwalsh** [comment]
Gotcha, could you please fix the formatting so we can get this merged?

**Comment by gladuo** [comment]
`black .` Done.

CHANGELOG could be like...

MOD correct a_gold and a_pred positions … a6cfeb9
ADD datatype for tensor … 1fc9a15
ADD is_training to make predictor work … 126b7e0

**Pull request merged**
