### PR TITLE
BART based (passage, answer) --> question generation model 

### PR DESCRIPTION
**Pull request by nitishgupta**
Given a passage with a span marked as the answer, fine-tune a BART model to generate a relevant question.

The dataset-reader is specific to SQuAD but the model is dataset agnostic.

PR contains a dataset reader, model, and a predictor.

### CODE REVIEW

**Comment by nitishgupta** [comment]
@matt-gardner The test for the model fails as it cannot find the dataset-reader registered with "squad_question_generation" which is present and registered. Regular training with that reader works. Would you know what the issue might be?

**Comment by matt-gardner** [comment]
On the registration error: I think that modifying the `__init__.py` files in the relevant modules should be enough.  You need to import your classes there, so they actually get registered.  I'm not sure why "regular training" succeeds for you locally, though.

**Review by matt-gardner — COMMENTED** [review]
I haven't looked too closely at the model yet; what exactly had to change from the other BART model that we have?

**Comment by nelson-liu** [comment]
this looks useful, thanks @nitishgupta ! Any plans on addressing Matt's comments in the near future (np if not, just wondering)?

**Comment by matt-gardner** [comment]
ICLR deadline is Friday morning; I'd guess work on this will pick up a bit after that.

**Comment by nitishgupta** [comment]
Yes, I plan to get back to this then.

**Pull request closed without merging**
